package enums;

public enum Resources {
	ANNOUNCEMENTS, CITATIONS, COMMENTS, CREDITS, CURATION, DOWNLOADS, EXPERIMENTS,
	EXTERNALS, FAVOURITES, FILES, GROUPS, INTERNALS, JOBS, LICENSES, MESSAGES,
	ONTOLOGIES, PACKS, PICTURES, PREDICATES, RATINGS, RELATIONSHIPS, REVIEWS,
	RUNNERS, TAGS, TAGGINGS, TYPES, USER, WORKFLOW

}
